version: '3.8'

services:
  codelab:
    build: .
    container_name: codelab_server
    ports:
      - "3000:3000"
      - "8080:8080"
      - "2222:2222"
    volumes:
      - ./data:/app/data:Z
    userns_mode: "keep-id"
    environment:
      - REPO_STORAGE_PATH=/app/data/repositories/
      - DB_PATH=/app/data/db/codelab.db
      - DB_SCHEMA_PATH=/app/db/schema.sql
    restart: no